# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storageApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_notes', to='storageApp.Note'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
