# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-09 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storageApp', '0002_auto_20191008_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_notes', to='storageApp.Note'),
        ),
    ]
