# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-09 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageApp', '0005_auto_20191009_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
